# Generated by Django 4.2 on 2023-05-01 00:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('messaging', '0005_remove_message_professor_remove_message_student_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='parent_msg',
        ),
        migrations.RemoveField(
            model_name='message',
            name='subject',
        ),
        migrations.AlterField(
            model_name='message',
            name='receiver',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='receiver_messages', to=settings.AUTH_USER_MODEL, verbose_name='Recipient'),
            preserve_default=False,
        ),
    ]
