# Generated by Django 4.2 on 2023-04-16 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentview', '0002_remove_studentticket_classname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='classwaitlist',
            name='closed',
            field=models.BooleanField(default=False),
        ),
    ]
