# Generated by Django 4.2 on 2023-04-18 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentview', '0003_classwaitlist_closed'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentticket',
            name='position',
            field=models.IntegerField(default=0),
        ),
    ]
