# Generated by Django 4.2 on 2023-04-22 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentview', '0004_studentticket_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentticket',
            name='waitlist_status',
            field=models.CharField(default='p', max_length=1),
        ),
    ]
