# Generated by Django 4.2 on 2023-04-23 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("studentview", "0005_studentticket_waitlist_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="classwaitlist",
            name="classDescription",
            field=models.TextField(default="", verbose_name="Description"),
        ),
        migrations.AlterField(
            model_name="classwaitlist",
            name="classCode",
            field=models.CharField(max_length=200, verbose_name="Class Code"),
        ),
        migrations.AlterField(
            model_name="classwaitlist",
            name="className",
            field=models.CharField(max_length=200, verbose_name="Class Name"),
        ),
        migrations.AlterField(
            model_name="classwaitlist",
            name="crn",
            field=models.IntegerField(default=0, verbose_name="CRN"),
        ),
        migrations.AlterField(
            model_name="classwaitlist",
            name="schedule",
            field=models.CharField(max_length=200, verbose_name="Schedule"),
        ),
        migrations.AlterField(
            model_name="classwaitlist",
            name="sortType",
            field=models.CharField(max_length=200, verbose_name="Sort Type"),
        ),
        migrations.AlterField(
            model_name="classwaitlist",
            name="term",
            field=models.CharField(max_length=200, verbose_name="Term"),
        ),
    ]
