# Generated by Django 4.2 on 2023-04-24 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentview', '0006_classwaitlist_classdescription_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='classwaitlist',
            name='anonymous_waitlist',
            field=models.BooleanField(default=False, verbose_name='Anonymous Waitlist'),
        ),
        migrations.AlterField(
            model_name='classwaitlist',
            name='classDescription',
            field=models.TextField(default=' ', verbose_name='Description'),
        ),
    ]
