# Generated by Django 4.2 on 2023-04-29 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentview', '0007_classwaitlist_anonymous_waitlist_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='classwaitlist',
            name='archived',
            field=models.BooleanField(default=False, verbose_name='Archived'),
        ),
    ]
