# Generated by Django 4.2 on 2023-04-30 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentview', '0008_classwaitlist_archived'),
    ]

    operations = [
        migrations.AddField(
            model_name='classwaitlist',
            name='request_academic_status',
            field=models.BooleanField(default=False, verbose_name='Request Academic Status'),
        ),
        migrations.AddField(
            model_name='classwaitlist',
            name='request_major',
            field=models.BooleanField(default=False, verbose_name='Request Major'),
        ),
        migrations.AddField(
            model_name='classwaitlist',
            name='request_msg',
            field=models.BooleanField(default=False, verbose_name='Request Message'),
        ),
        migrations.AddField(
            model_name='studentticket',
            name='msg',
            field=models.CharField(default='', max_length=200, verbose_name='Message for Professor'),
        ),
        migrations.AddField(
            model_name='studentticket',
            name='student_academic_status',
            field=models.CharField(default='', max_length=20, verbose_name='Academic Status'),
        ),
        migrations.AddField(
            model_name='studentticket',
            name='student_major',
            field=models.CharField(default='', max_length=100, verbose_name='Major'),
        ),
    ]
