# Generated by Django 4.2 on 2023-04-11 22:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassWaitlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('className', models.CharField(max_length=200)),
                ('classCode', models.CharField(max_length=200)),
                ('crn', models.IntegerField(default=0)),
                ('schedule', models.CharField(max_length=200)),
                ('sortType', models.CharField(max_length=200)),
                ('term', models.CharField(max_length=200)),
                ('date_added', models.DateTimeField(verbose_name='date published')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'class_waitlist',
            },
        ),
        migrations.CreateModel(
            name='StudentTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_joined', models.DateTimeField(verbose_name='date joined')),
                ('class_waitlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studentview.classwaitlist')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'student_ticket',
            },
        ),
    ]
