# Generated by Django 4.2 on 2023-04-13 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentview', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classwaitlist',
            name='classCode',
            field=models.CharField(db_column='class_code', max_length=200),
        ),
        migrations.AlterField(
            model_name='classwaitlist',
            name='className',
            field=models.CharField(db_column='class_name', max_length=200),
        ),
        migrations.AlterField(
            model_name='classwaitlist',
            name='sortType',
            field=models.CharField(db_column='sort_type', max_length=200),
        ),
    ]
